### ISSUE TITLE
Ссылки и кнопки для попапа

### ISSUE THREAD

**Issue by foxhable** [aaccent/reset_layout#1]
Что должны делать кнопки и ссылки при нажатии:

1. "Получить консультацию" в шапке открывает попап с формой
2. "Цены" и "Акции" в шапке и футере открывает попап с формой
3. "Отзывы" в шапке и футере скролит к `section.about-us`
4. "О клинике" в шапке и футере скролит к "section.our-advantages"
5. "Контакты" в шапке и футере скролит к `section.call-us`
6. Ссылки в секции с "Комплекс услуг платной скорой медицинской помощи" открывают попап с формой

<details><summary>Скрин секции "Комплекс услуг платной скорой медицинской помощи"</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/d540890a-2912-4e33-8cd2-cde1f9d001e3)
</details> 

7. Ссылки в меню услуг шапки и футере открывают попап с формой
8. Кнопка "Подробнее о компании" вызывает попап с формой

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/cef957b3-792e-4511-b308-2f62c642a23f)
</details>

**Comment by RamizAshurov** [comment]
1. Сделано
2. Сделано
3. Cделано
4. Сделано
5. Сделано
6. Сделано
7. Сделано
8. Сделано
