### ISSUE TITLE
"Показать полностью" в сео блоке

### ISSUE THREAD

**Issue by foxhable** [aaccent/reset_layout#10]
При нажатии ничего не происходит. Если текста для скрытия недостаточно, то кнопка должна пропасть

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/6d32cbf2-454c-492d-85d4-a4b649d6b9c5)
</details>

**Comment by RamizAshurov** [comment]
Сделано
