### ISSUE TITLE
Градиент на фоне

### ISSUE THREAD

**Issue by foxhable** [aaccent/reset_layout#12]
В макете у секций с темным фоном - `.why-we`, `.contact-us`, `.about-us` и `.call-us` и есть градиент `linear-gradient(180deg, #0D1B1F 0%, #111D26 100%)` и белый элемент.

<details><summary>Пример белого элемента</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/7815a55d-2209-4b04-a982-8a7e3150ee5c)
</details> 

<details><summary>Скрин секции why-we</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/e7362fbf-9992-401c-8ae9-fbdcb3714e12)
</details> 

<details><summary>Скрин секции contact-us</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/8bdeb28f-9d0e-4c80-8ea3-b5b844acae63)
</details> 

<details><summary>Скрин секции about-us</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/31a45577-41c1-447f-8d3c-54f1e9512cb6)
</details> 

<details><summary>Скрин секции call-us</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/9008b14b-0c5e-41ce-beb7-6ef57650e8f6)
</details>

**Comment by RamizAshurov** [comment]
Исправил
