### ISSUE TITLE
Футер

### ISSUE THREAD

**Issue by foxhable** [aaccent/reset_layout#16]
1. Соц сети должны быть 4 элемента в ряд без переноса

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/646ac411-ce63-4161-9df7-b4aa509e8f64)
</details> 

2. "Имеются противопоказания" должны быть в одну строку

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/307fbaa4-f343-47b3-b824-5aa62b8b8ed3)
</details>

**Comment by RamizAshurov** [comment]
Исправил. На экранах с шириной < 1680px соцсети переносятся на следующий ряд, если не хватает места

**Comment by foxhable** [comment]
Не должно быть так. На этих ширинах все ещё можно уместить как на макете. Можно пожертвовать шириной элемента `.footer__menu`, чтобы вместилось.

<details><summary>Скрин футер__меню</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/2c47a1e8-b283-4434-b62c-d5271bc7b44a)
</details>

**Comment by RamizAshurov** [comment]
Исправил
