### ISSUE TITLE
`cursor: pointer` на не кнопках

### ISSUE THREAD

**Issue by foxhable** [aaccent/reset_layout#2]
На некоторых `div`'ах есть класс `button` и из-за этого у них `cursor: pointer`, но сами они не кликабельные. Убери `pointer` с класса. У `button` и так по умолчанию этот курсор стоит

<details><summary>Скрин элемента с классом</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/827cf304-cce8-4159-8f1d-9683a9f5dfea)
</details>

**Comment by RamizAshurov** [comment]
Сделано
