### ISSUE TITLE
Ссылки

### ISSUE THREAD

**Issue by foxhable** [aaccent/reset_layout#21]
Ссылки, которые открывают попапы нужны были для лэндинга, а далее мы верстаем для сборки на битриксе, поэтому нужно вернуть то, что было для лэндинга:
1. Ссылки в меню услуг шапки и футера не открывают попап звонка
3. "Подробнее о компании" в секции "Особое внимание клиенту" не открывает попап
4. Ссылки в секции с "Комплекс услуг платной скорой медицинской помощи" не открывают попап с формой

**Comment by RamizAshurov** [comment]
1. Сделано
2. Исправил
3. Исправил
