### ISSUE TITLE
Контакты мобилка

### ISSUE THREAD

**Issue by foxhable** [aaccent/reset_layout#25]
1. Номер, мыло и гео в макете "прибиты" к левому краю
<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/16f5dd2d-41d6-4ab1-adc5-3d81e2f9a1d6)
</details> 
2. Расстояние между соц сетями и формой в макете `30px`
<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/64cbbc27-033c-47e7-8312-188b34150023)
</details> 
3. Кнопки в макете `55px`
<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/700418f3-04f3-4851-93aa-363867b1c1dd)
</details> 
4. Между картой и фоном контейнера в макете `10px`
<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/14638b1d-b4a3-4e79-a499-8b1ae0521200)
</details> 
5. Между картой и реквизитами в макете `30px`
<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/928bc766-af80-457d-9af8-ef868819eba6)
</details>

**Comment by RamizAshurov** [comment]
1. Исправил
2. Исправил
3. Исправил
4. Исправил
5. Исправил

**Comment by foxhable** [comment]
`border-radius` у карты в макете `10px`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/195dbfc4-dad9-4cb1-9f59-7900f5a543d1)
</details>

**Comment by RamizAshurov** [comment]
Исправил
