### ISSUE TITLE
Остались вопросы?

### ISSUE THREAD

**Issue by foxhable** [aaccent/reset_layout#28]
1. На страницах "Цены", "Подуслуга" и "Акция" блок с формой справа от контента должен быть `sticky`.
2. Не видно заднего фона у полей. В макете "Подуслуга" это ошибка скорее всего. В макете "Цены" задний фон есть
<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/c50a7318-a437-4bb3-b695-850bef17db62)
</details> 
3. Поменять `h5` на `div`
<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/e1a6d590-e94b-472e-b133-655a531ea571)
</details>

**Comment by RamizAshurov** [comment]
1. Исправил
2. Исправил
3. Исправил
