### ISSUE TITLE
Вызвать врача в услугах

### ISSUE THREAD

**Issue by foxhable** [aaccent/reset_layout#29]
На странице "Услуга" и "Подуслуга" кнопка "Вызвать врача" должен открывать попап звонка

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/5d0576e6-b72d-4d6e-a20d-01bf2d31f32d)
</details>

**Comment by RamizAshurov** [comment]
Исправил
