### ISSUE TITLE
`h*` заголовки

### ISSUE THREAD

**Issue by foxhable** [aaccent/reset_layout#3]
Небольшой список рекомендаций и правил для расстановки `h*` заголовков:
https://knowledge.aaccent.ru/layout-process.html#h-titles

1. В слайдере первого блока `h2` сделай `div`, а у первого слайда сделай `h1`. На странице обязательно должен быть `h1`, но он не может быть после `h2`. Сами `h*` заголовки лучше для сео не размещать в таких слайдерах.

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/3157977c-6b61-409e-b60c-e1d5187c361c)
</details> 

2. В секции с услугами `h4.service__name` сделай тэгом `div`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/beeef5b8-d76d-4a7f-8d35-7ca341b3645f)
</details> 

3. В секции "Почему выбирают нас" элементы `h4.advantage__name` сделай тэгом `div`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/1d30191a-e205-47a6-9a63-39e6efecdec4)
</details> 

4. В той же секции элемент `h3.order-call__title` сделай тэгом `div`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/5335c5b6-6ef2-467f-85bb-030c930180d1)
</details> 

5. Имена докторов сделай `div`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/cfcf2fb1-4d62-453b-8774-c285e808235c)
</details> 

6. В секции "Как заказать скорую помощь" элементы `h4.step__name` сделай `div`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/314f74b2-88df-4c47-9c90-153989d001a7)
</details> 

7. В попапе "В каких ситуация требуется вызов" заголовок сделать `div`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/22b398f6-01de-41d0-9259-0df56dd7458a)
</details> 

8. В попапе звонка заголовок сделать `div`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/ad739346-a9c6-4f43-b976-aa719e7d9713)
</details> 

9. В секции с формой текст "Пишите, звоните по номеру" сделать `div`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/59a9ce57-0988-4f99-af03-1c010d3a6aab)
</details> 

10. В секции с лицензиями заголовок сделать `h4`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/efa6f608-f78f-4f56-aa02-bdbc9320de9b)
</details> 

11. В сео блоке заголовок сделать `h2`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/5e9e10ca-432b-4598-b0ec-49996e21622c)
</details> 

12. В секции с формой перед футером "оставьте заявку" сделать `div`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/4ae8d42f-1d3d-4a1c-b326-1b998d1cc87c)
</details> 

13. В футере заголовки секций сделать `div`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/a018ce0f-c211-4998-8367-62f74e852669)
</details>

**Comment by RamizAshurov** [comment]
1. Сделано
2. Сделано
3. Сделано
4. Сделано
5. Сделано
6. Сделано
7. Сделано
8. Сделано
9. Сделано
10. Сделано
11. Сделано
12. Сделано
13. Сделано

**Comment by foxhable** [comment]
1. 10 ошибся, хотел написать `h2`
2. Названия сертификатов сделай `div`
<details><summary>Скрин названий сертификатов</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/19a8ea00-04f6-48d7-b120-035cc49865b5)
</details>

**Comment by RamizAshurov** [comment]
Исправил
