### ISSUE TITLE
Услуги

### ISSUE THREAD

**Issue by foxhable** [aaccent/reset_layout#31]
1. Секция "Услуги по оказанию мед помощи" сломалась на странице "Услуги"
<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/ab618a47-c72b-41fc-ac53-43d335b5f1fc)
</details> 
2. На мобилке в секции "Медицинские услуги на дому" между фоткой и фоном больше расстояние снизу, чем в макете
<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/a0a80dbb-36b5-48d9-b5e8-73e9b0cf78f8)
</details>

**Comment by RamizAshurov** [comment]
1. Исправил
2. Исправил

**Comment by foxhable** [comment]
2 Не исправилось

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/798afc48-0fc8-4685-8d7c-21a2a9f6e24c)
</details>

**Comment by RamizAshurov** [comment]
Исправил
