### ISSUE TITLE
Контент шаги

### ISSUE THREAD

**Issue by foxhable** [aaccent/reset_layout#32]
В пронумерованном списке контента цифры должны быть "прибиты" к верху текста

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/867998cc-8240-4ca4-b988-581272bac081)
</details>

**Comment by RamizAshurov** [comment]
Исправил

**Comment by foxhable** [comment]
Не заметил, что на пк одиночные строки выравниваются по центру. Вроде это невозможно, поэтому сделай, чтобы для пк было по центру, а на мобилке прибито к верху

**Comment by RamizAshurov** [comment]
Исправил
