### ISSUE TITLE
Содержание статьи

### ISSUE THREAD

**Issue by foxhable** [aaccent/reset_layout#36]
1. Содержание должно генерироваться через JS на основе `h2` заголовков, его не должно быть в разметке изначально.
2. На мобилке селектор не работает

**Comment by RamizAshurov** [comment]
1. Исправил. У все заголовков на странице должен быть тег h2? Изначально у первого заголовка стояло h2, у остальных - h4
2. Исправил

**Comment by foxhable** [comment]
1. `h4` на практике очень-очень редко используют, даже `h3` почти не используется. В статьях большее время только `h2` используют
2. "Правовая информация" `h1` сделай.
3. При создании содержания генерируй `id` через `crypto.randomUUID()` и используй для якорной ссылки в элементах содержания

**Comment by RamizAshurov** [comment]
1. Как быть с этим заголовком
![image](https://github.com/aaccent/reset_layout/assets/37570516/41366301-ce7a-4d8f-bcef-f6ce45487773)
2. Поправил теги заголовков, убрал дивы
3. Добавил генерацию через crypto.randomUUID()

**Comment by foxhable** [comment]
1. Как есть оставь

**Проблема:**
Не переключается активный элемент при скроле и клике

**Comment by RamizAshurov** [comment]
Исправил
