### ISSUE TITLE
Артикул услуги в ценах

### ISSUE THREAD

**Issue by foxhable** [aaccent/reset_layout#37]
Давай её сделаем `inline` и сунем в название, чтобы она вместе с текстом переносилась. А то на мобилке херово выглядит

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/b877fef0-f59b-46da-8ad8-1beedc0ccdbe)
</details>

**Comment by RamizAshurov** [comment]
Исправил
