### ISSUE TITLE
`p` в текстах

### ISSUE THREAD

**Issue by foxhable** [aaccent/reset_layout#5]
Во время сборки все текста превращаются в редактируемую область, куда можно будет вставить любую разметку. Если элемент с текстом будет тэгом `p`, то это создаст проблемы, т.к. кто-то может вставить внутрь ещё один `p`. Поэтому элементы с текстами должны быть `div`, а текст внутри либо в `p` без классов, либо без тэгов

```html
<div class="hero-slide__desc">
  <p>Some text</p>
</div>
``` 
--- или ---
```html
<div class="hero-slide__desc">
  Some text
</div>
``` 

**Изменить следующие элементы:**

1. В слайдер в первом блоке `p.hero-slide__desc` сделать `div` тэгом 

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/71fc80e9-dc90-45e8-afc0-b4646d8b35a9)
</details> 

2. Текст в "Почему выбирают нас" поместить в `div`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/342e18ad-afe0-4bcb-b4ac-2dffe2fc6198)
</details> 

3. В шагах у секции "Как заказать" тэг заменить на `div`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/6880045a-00e8-4f86-86bc-10cbe02273b3)
</details> 

4. В секции "В каких ситуациях требуется вызов" тэг текста заменить на `div`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/a75b7f8d-3850-41d4-9eaa-159c570d1e02)
</details>

**Comment by RamizAshurov** [comment]
1. Сделано
2. Сделано
3. Сделано
4. Сделано
