### ISSUE TITLE
Ссылка на политику

### ISSUE THREAD

**Issue by foxhable** [aaccent/reset_layout#6]
В тексте "Нажимая на кнопку «Заказать звонок» вы соглашаетесь с политикой конфиденциальности сайта" у форм, текст "политикой конфиденциальности" должно быть ссылкой

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/5216baab-2cd1-4a6b-abbb-c44fb776506e)
</details>

**Comment by RamizAshurov** [comment]
Сделано

**Comment by foxhable** [comment]
1. В секции "Получите полный комплекс" не сделал

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/4f66a72f-a9e3-49da-8577-5cd323a4fe32)
</details> 

2. В попапе не сделал

**Comment by RamizAshurov** [comment]
Исправил
