### ISSUE TITLE
Задайте вопрос

### ISSUE THREAD

**Issue by foxhable** [aaccent/reset_layout#9]
Там не `textarea`, просто `div`, а кнопка открывает попап вызова. Полей никаких дополнительно не нужно

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/reset_layout/assets/36298346/8c5d7cc2-745a-4097-980c-309119dfe7d1)
</details>

**Comment by RamizAshurov** [comment]
Исправил

**Comment by RamizAshurov** [comment]
Исправил
